# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='normal_schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='normal_schedule_active',
            field=models.DateField(blank=True, null=True),
        ),
    ]
