# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='docket',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='task',
            name='daily_time_amount',
        ),
        migrations.RemoveField(
            model_name='task',
            name='done_today',
        ),
        migrations.RemoveField(
            model_name='task',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_estimate',
        ),
        migrations.AddField(
            model_name='task',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='snooze_until',
            field=models.DateTimeField(null=True),
        ),
    ]
