# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Docket',
        ),
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Task',
        ),
    ]
