# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20170902_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='sis_password',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='sis_username',
        ),
    ]
