# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20160920_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='docket',
        ),
    ]
