# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-05 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20160920_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='should_update',
            field=models.DateField(null=True),
        ),
    ]
