# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-05 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_task_should_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='should_update',
        ),
    ]
