# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='message',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
